prviewer.remote.scheme=http
#prviewer.remote.host=apaas.cmbc.com.cn
prviewer.remote.host=apaas.uat.cmbc.cn
prviewer.remote.port=80
prviewer.api.list.path=/pset/api/gitee-api/pull-request-reviews/pullRequestsList
prviewer.api.detail.path=/pset/api/gitee/selectPullRequestInfos
prviewer.api.noteList.path=/pset/api/gitee/noteList
prviewer.api.note.path=/pset/api/gitee/note
prviewer.api.reply.path=/pset/api/gitee/replyNote
prviewer.api.resolve.path=/pset/api/gitee/resoveNote
prviewer.api.review.path=/pset/api/gitee/reviewsPr
prviewer.api.merge.path=/pset/api/gitee/mergeRepoPullRequestByUser
prviewer.api.deletePr.path=/pset/api/gitee/deletePRByUser
prviewer.api.closePr.path=/pset/api/gitee/closePRByUser
prviewer.api.updatePr.path=/pset/api/gitee/updatePRByUser
prviewer.api.aiReviewPrDetail.path=/pset/api/gitee/queryAiReviewPrDetailData
prviewer.api.aiReviewFileDetail.path=/pset/api/gitee/queryAiReviewFileIssueDetailData
prviewer.api.aiHandleIssue.path=/pset/api/gitee/handleAiReviewIssue
prviewer.api.triggerAiReview.path=/pset/api/gitee/allPRllmStream.json
prviewer.api.createPr.path=/pset/api/gitee/createPRByUser
prviewer.api.developers.path=/pset/api/gitee/getDevelopers
prviewer.api.repoMemberRole.path=/pset/api/gitee/getRepoMemberRole
prviewer.api.canCreatePr.path=/pset/api/gitee/canCreatePR
prviewer.api.pageSize=20
prviewer.mock.enabled=true
prviewer.mock.dir=mock
prviewer.mock.list.file=pr-list.json
prviewer.mock.detail.file=pr-detail.json
prviewer.mock.issues.file=pr-issues.json
prviewer.mock.repoMemberRole.file=repo-member-role.json
prviewer.mock.canCreatePr.file=can-create-pr.json
prviewer.mock.developers.file=developers.json
prviewer.mock.createPr.file=create-pr.json
prviewer.ui.font.size=12
prviewer.security.pluginAuthor.publicKey=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCDOFI86EuqXJvDKqqHbwH5a7hJscjfkA1qHQxFawLkrG27ZmL1rVyPSDbJx5acCDfvwIaQxseglhKFYgXK3H26NFBMV1XuwXD/Mm4UH4XwuZFck06+RZPVvDrJmsSdAD0rHDxS6C32X94ZqEsswLnJ0iNTvBu7HlpsJBPJqc0QfQIDAQAB
prviewer.security.pluginAuthor.usernameEnv=USERID
